### ISSUE TITLE
devkitA64 scandir returns -1 if called when errno is nonzero

### ISSUE THREAD

**Issue by rsn8887** [devkitPro/newlib#13]
This was already discussed with @Stary2001 on Discord. The issue here is just for the record in case someone else struggles with this in the meantime.

The current implementation of scandir in devkitA64 fails if errno is non-zero at the time when scandir is called.

Expected behavior: the result of scandir should  not depend on any prior value of errno.

Proposed fix: set errno to zero at the beginning of scandir.

Workaround for now: replace `scandir(...)` with `errno = 0; scandir(...)`

**Comment by WinterMute** [comment]
Fixed with https://github.com/devkitPro/newlib/commit/dc6ace5796746a518866f82dd4c97ce73abb59e9
