### ISSUE TITLE
devkitPPC r29 ftruncate

### ISSUE THREAD

**Issue by Oibaf66** [devkitPro/newlib#2]
In devkitPPC release 29, the compiler gives a warning for "ftruncate" (undefined function).
However the compiler can link the function.

This is due to sys/unistd.h
#if defined(__CYGWIN__) || defined(__rtems__) || defined(__aarch64__) || defined (__arm__) || defined(__sh__) || defined(__SPU__)
#if !defined(__INSIDE_CYGWIN__)
int     _EXFUN(ftruncate, (int __fd, off_t __length));
int     _EXFUN(truncate, (const char *, off_t __length));
#endif
#endif

where PPC architecture is not included in the "#if defined" list.

**Comment by WinterMute** [comment]
fixed with r29-1
