### ISSUE TITLE
libsysbase returns DT_REG in readdir() for anything that isn't a directory

### ISSUE THREAD

**Issue by Crementif** [devkitPro/newlib#24]
As you can see at https://github.com/devkitPro/newlib/blob/devkitPPC/libgloss/libsysbase/dirent.c#L172, it will return DT_REG if a devoptab returns DT_LNK or DT_UNKNOWN.

I've found this problem while working on improved devoptabs for [wut](https://github.com/devkitpro/wut) and [libiosuhax](https://github.com/Crementif/libiosuhax) for the Wii U to support the Wii U's symlink variant. It'd help a lot since currently even though it doesn't return DT_UNKNOWN you have to ignore it and call lstat to check for the proper type.

I can make a pull request, but I wasn't too sure which branch I should apply it too so I thought I should open an issue first. I've tested it and if we used the same macro from https://github.com/devkitPro/newlib/blob/devkitPPC/winsup/cygwin/include/sys/dirent.h#L89-L90 it would work for all types properly.

**Comment by WinterMute** [comment]
fixed with https://github.com/devkitPro/newlib/commit/9303352d01f3f8b3601675a93f7a63c900a871ad

The new realpath implementation will also resolve symlinks given a readlink implementation in devoptab.
