### ISSUE TITLE
calling printf when stdout isnt open

### ISSUE THREAD

**Issue by Lectem** [devkitPro/newlib#3]
See https://github.com/smealum/ctrulib/issues/118

**Comment by WinterMute** [comment]
Might be helpful if you had some code illustrating the issue. There's not enough information here to reproduce the problem.

**Comment by Lectem** [comment]
I sadly can't reproduce it anymore with latest ctrulib, and I can't find which of my programs triggered this (it's been several months).
I'll just close the issue then.
