### ISSUE TITLE
Nonconforming return type of `ftell`

### ISSUE THREAD

**Issue by FrankHB** [devkitPro/newlib#5]
Today I migrated my environment to `pacman` based one, using devkitARM r48-2 and I found some of my code failed to build. I found the return type of `ftell` in the file `arm-none-eabi/include/stdio.h` is `off_t` rather than `long`. This is not conforming to any version of ISO C and POSIX. The document of newlib I've found also shows it should be `long`.

Strangely, the code in https://github.com/devkitPro/newlib/blob/c17b0f00820c6c5187944800b6b4c3b83fe71293/newlib/libc/include/stdio.h#L236 is correct, but it is different to the file above (in the package). Not very sure if it should be the issue here, but it is likely to be.

**Comment by WinterMute** [comment]
fixed with latest newlib patches
