### ISSUE TITLE
devkitPPC: Undefined reference to `posix_memalign' when using aligned_alloc

### ISSUE THREAD

**Issue by exjam** [devkitPro/newlib#7]
aligned_alloc is defined to use posix_memalign:
https://github.com/devkitPro/newlib/blob/devkitPPC_r31/newlib/libc/stdlib/aligned_alloc.c

aligned_alloc is a stanadard C11 function:
http://en.cppreference.com/w/c/memory/aligned_alloc

I can confirm memalign does work so I guess maybe the fix would be to change aligned_alloc to use memalign instead of posix_memalign? I'm not sure so that's why I went for an Issue instead of a Pull request.

**Comment by WinterMute** [comment]
Fixed with latest newlib patches
